apiVersion: v1
kind: Service
metadata:
    name: "anilsdemoaks-ded1"
    labels:
        app: "anilsdemoaks-ded1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "anilsdemoaks-ded1"